module Scrapegraphai
  module Models
    type healthz_check_params =
      {  } & Scrapegraphai::Internal::Type::request_parameters

    class HealthzCheckParams < Scrapegraphai::Internal::Type::BaseModel
      extend Scrapegraphai::Internal::Type::RequestParameters::Converter
      include Scrapegraphai::Internal::Type::RequestParameters

      def initialize: (?request_options: Scrapegraphai::request_opts) -> void

      def to_hash: -> { request_options: Scrapegraphai::RequestOptions }
    end
  end
end
